#!/bin/bash

jekyll build

$ERRORSTRING="Error. Please make sure you've indicated correct parameters"
if [ $# -eq 0 ]
  then
    echo $ERRORSTRING;
elif [ $1 == "live" ]
  then
    if [[ -z $2 ]]
      then
        echo "Running dry-run"
        rsync --dry-run -az --force --delete --progress -e "ssh -p22" ./_site/ deploy@fynt.ca:/srv/www/keithsilgard/public
    elif [ $2 == "go" ]
      then
        echo "Running actual deploy"
        rsync -az --force --delete --progress -e "ssh -p22" ./_site/ deploy@fynt.ca:/srv/www/keithsilgard/public
    else
      echo $ERRORSTRING;
    fi
fi